import "./globals.css";
import { Inter } from "next/font/google";

// import Navbar from "../components/navbar";
import NavbarComp from "@/pages/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKEKsVytN1tvBbQK7DRxJH3h8cO5tugQdLieTC7ahbsZJr0MLnseGqPsxkjjcb8bZIv5o&usqp=CAU"
        />
      </head>
      <body className={inter.className}>
        <nav>
          <NavbarComp />
        </nav>
        {children}
      </body>
    </html>
  );
}
